### ISSUE TITLE
"get-pfaConnectionlfromRDM"  not exist.  

### ISSUE THREAD

**Issue by kenchg** [PureStorage-OpenConnect/PureStorage.FlashArray.VMware#1]
Remove the extra "l" of "get-pfaConnectionlfromRDM" in code could fix this.     

-----------Error message-------------
PS> remove-pfaVolRDM -rdm $rdm -flasharray $purepoc01
get-pfaConnectionlfromRDM : The term 'get-pfaConnectionlfromRDM' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by codyhosterman** [comment]
Oh fat fingered... I will fix this I dont know how I missed this.

**Comment by codyhosterman** [comment]
Fixed in RDM module 1.0.0.3
