### ISSUE TITLE
Port group not working for dvs

### ISSUE THREAD

**Issue by WuTangDangie** [PureStorage-OpenConnect/PureStorage.FlashArray.VMware#2]
The port group parameter didn’t seem to work with distributed port groups. I had to create a standard vswitch and port group to get it to work.

Deploy-PfaAppliance : Cannot process argument transformation on parameter ‘portGroup’. Cannot convert the “dvspg-name” value of type
“VMware.VimAutomation.ViCore.Impl.V1.Host.Networking.DistributedPortGroupImpl” to type
“VMware.VimAutomation.ViCore.Types.V1.Host.Networking.VirtualPortGroup”.

**Comment by codyhosterman** [comment]
Will fix this in the next release.

**Comment by codyhosterman** [comment]
Okay fixed in configuration module 1.3.1.0 which is included in PureStorage.FlashArray.VMware version 1.2.4.2
