### ISSUE TITLE
Add -installed parameter to get-pfavsphereplugin to get the currently installed version.

### ISSUE THREAD

**Issue by dstamen** [PureStorage-OpenConnect/PureStorage.FlashArray.VMware#26]
Feature Request

**Comment by codyhosterman** [comment]
Complete. Added a -Server parameter. So if you pass in one or more vCenters, it will return the plugins installed on them, the version, type and download URL. You can optionally specify -flash or -html. If you do not specify a vCenter it will return the available source versions like before. It will not use the default vCenter connections if no server is specified so it does not break current behavior. Available starting with 2.0.0.0
