### ISSUE TITLE
Add Older Versions of Plugin for Install Options

### ISSUE THREAD

**Issue by Carvertown** [PureStorage-OpenConnect/PureStorage.FlashArray.VMware#4]
For 90% of the use cases, installing the most recent plugin will generally be used.  However, in the event that a new plugin version is causing problems, has a bug or in the end the customer needs to install a older version we should make sure we have at least one version behind the newest available to install.

**Comment by codyhosterman** [comment]
This is completed. Update to at least version 1.4.1.0 or later. The Get-PfavSpherePlugin function now has a switch parameter:

```
PS C:\Users\Cody Hosterman> Get-PfavSpherePlugin -previous


Source Type   Version
------ ----   -------
Pure1  Flash  3.1.3
Pure1  Flash  3.1.1
Pure1  Flash  3.1.2
Pure1  HTML-5 4.2.0
Pure1  HTML-5 4.0.0
Pure1  HTML-5 4.1.0

```
This will list older versions of the plugin a few releases back.

The Install-PfavSpherePlugin cmdlet can then install older versions by specifying the old version in the version parameter:

`Install-PfavSpherePlugin -Version 3.1.2`
