### ISSUE TITLE
PS C:\Windows\system32> copy-pfaVvolVmdkToNewVvolVmdk -TargetVm $vm -Vmdk $hdisk   error messages

### ISSUE THREAD

**Issue by PascalStordata** [PureStorage-OpenConnect/PureStorage.FlashArray.VMware#54]
Hello,

I'm working for Stordata (French PURE Storage Partner)

It's regarding the following PURE Storage powershell commandlet below:

PS C:\Windows\system32> copy-pfaVvolVmdkToNewVvolVmdk -TargetVm $vm -Vmdk $hdisk

It clones directly from the disk of a previously chosen source VM
This is successful but it returns the following errors after execution:
It seems that some commands are no more available.

AVERTISSEMENT : The 'Version' property of VirtualMachine type is deprecated. Use the 'HardwareVersion' property instead.
New-HardDisk : 02/11/2020 17:43:09 New-HardDisk Impossible de charger le fichier ou l'assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ou une de ses
dépendances. Le fichier spécifié est introuvable.
Au caractère C:\Program Files\WindowsPowerShell\Modules\PureStorage.FlashArray.VMware.VVol\2.0.0.0\PureStorage.FlashArray.VMware.Vvol.psm1:468 : 20
+ ... wHardDisk = New-HardDisk -Datastore $datastore -CapacityGB $vmdk.Capa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [New-HardDisk], ViError
+ FullyQualifiedErrorId : Client20_VirtualDeviceServiceImpl_NewVirtualHardDisk_ReconfigError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.NewHardDisk

Get-VvolUuidFromVmdk : Impossible de lier l'argument au paramètre « Vmdk », car il a la valeur Null.
Au caractère C:\Program Files\WindowsPowerShell\Modules\PureStorage.FlashArray.VMware.VVol\2.0.0.0\PureStorage.FlashArray.VMware.Vvol.psm1:469 : 47
+ $newVvolUuid = get-vvolUuidFromVmdk -vmdk $newHardDisk
+ ~~~~~~~~~~~~
+ CategoryInfo : InvalidData : (:) [Get-VvolUuidFromVmdk], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-VvolUuidFromVmdk

Get-PfaVolumeNameFromVvolUuid : Impossible de lier l'argument au paramètre « VvolUUID », car il s'agit d'une chaîne vide.
Au caractère C:\Program Files\WindowsPowerShell\Modules\PureStorage.FlashArray.VMware.VVol\2.0.0.0\PureStorage.FlashArray.VMware.Vvol.psm1:470 : 76
+ ... get-PfaVolumeNameFromVvolUuid -flasharray $fa -vvolUUID $newVvolUuid
+ ~~~~~~~~~~~~
+ CategoryInfo : InvalidData : (:) [Get-PfaVolumeNameFromVvolUuid], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-PfaVolumeNameFromVvolUuid

Invoke-RestMethod : {"msg": "page not found"}
Au caractère C:\Program Files\WindowsPowerShell\Modules\PureStorage.FlashArray.VMware.Configuration\2.0.0.1\PureStorage.FlashArray.VMware.Configuration.psm1:1412 : 28
+ ... aResponse = Invoke-RestMethod -Method $restOperationType -Uri $apiend ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

The end customer is asking if PURE Storage could solved this bad behavior. (Errors messages)

Software versions :
VSphere 6.7 U3 
Purity 5.3.8 
Powershell (Windows server 2012R2) 

Thank you 

Best regards
Pascal LE FLOCH
Stordata

**Comment by codyhosterman** [comment]
Will take a look at this.

**Comment by codyhosterman** [comment]
I've done some research into this.

There are a few things:

1. - The warning about deprecation
2. - The new-harddisk error
3. - The subsequent errors.

1) The deprecation warning is actually from VMware's own PowerCLI cmdlet new-harddisk which is used by this cmdlet. There is nothing I can do about as VMware needs to fix their cmdlet, which I can reach out to them about, but what I can do is suppress the warning within the cmdlet.

2) This is likely due to the fact the customer is running this on Windows 2012 R2. Old libraries etc. It is causing the VMware PowerCLI cmdlets to fail to run due to an old or corrupted version of the Newtonsoft.Json file.

3) The subsequent failures are due to failure number 2. Since the VMDK is not returned properly the resulting operations do not have the information they need to run.

So I am going to do two things:

1. Suppress the warning and ask VMware to fix it
2. Add error handling so that the script ends on the first failure and does not create compounding failures

The customer needs to look into fixing the JSON library. There are some good references hereL
https://www.reddit.com/r/vmware/comments/8ifztv/issue_with_powercli_1010/
https://stackoverflow.com/questions/32794225/could-not-load-file-or-assembly-newtonsoft-json-version-7-0-0-0

There are many more. They can either do that, or use a newer version of Windows altogether (2016+)

**Comment by PascalStordata** [comment]
Hi Cody,

Thank you very much for your help.
Have a great day.

Best regards



[cid:image010.png@01D6E9DF.46C039F0]
Pascal LE FLOCH
Escalation Manager
pascal.lefloch@stordata.fr<mailto:pascal.lefloch@stordata.fr>

T : +33 1 30 21 71 71
M : +33 6 18 02 46 88
28, rue Saint-Honoré – 78000 VERSAILLES

www.stordata.fr<http://www.stordata.fr/>

Suivez-nous
[cid:image011.png@01D5BFFB.8E93B900]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.linkedin.com_company_stordata_&d=DwMGaQ&c=tEbGsWWjqkBSpaWdXc_mdMSanI1bDu-FKXiKGCfVmPM&r=KiBg1um17V9FPmcjoMEpYvsrxt1P_D40hxePLTkAOkQ&m=rrX92VitmaWZAjpRZFS1XLVV5bj7KfPOo2Ya2Qi0LQ4&s=CNl9ATRmn0QwpQrSV-3LkQyT0BSLabRHrNMti9088Mk&e=>[cid:image012.png@01D5BFFB.8E93B900]<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_GroupeStordata&d=DwMGaQ&c=tEbGsWWjqkBSpaWdXc_mdMSanI1bDu-FKXiKGCfVmPM&r=KiBg1um17V9FPmcjoMEpYvsrxt1P_D40hxePLTkAOkQ&m=rrX92VitmaWZAjpRZFS1XLVV5bj7KfPOo2Ya2Qi0LQ4&s=y9-hVXaNnHya23aRACYizX8m2KzurizzqlCvSV68Asc&e=>[cid:image013.png@01D5BFFB.8E93B900]<https://www.facebook.com/stordata>


De : Cody Hosterman <notifications@github.com>
Envoyé : mercredi 13 janvier 2021 18:09
À : PureStorage-OpenConnect/PureStorage.FlashArray.VMware <PureStorage.FlashArray.VMware@noreply.github.com>
Cc : Pascal LE FLOCH <Pascal.LEFLOCH@stordata.fr>; Author <author@noreply.github.com>
Objet : Re: [PureStorage-OpenConnect/PureStorage.FlashArray.VMware] PS C:\Windows\system32> copy-pfaVvolVmdkToNewVvolVmdk -TargetVm $vm -Vmdk $hdisk error messages (#54)



I've done some research into this.

There are a few things:
1.

     *   The warning about deprecation
2.

     *   The new-harddisk error
3.

     *   The subsequent errors.

  1.  The deprecation warning is actually from VMware's own PowerCLI cmdlet new-harddisk which is used by this cmdlet. There is nothing I can do about as VMware needs to fix their cmdlet, which I can reach out to them about, but what I can do is suppress the warning within the cmdlet.
  2.  This is likely due to the fact the customer is running this on Windows 2012 R2. Old libraries etc. It is causing the VMware PowerCLI cmdlets to fail to run due to an old or corrupted version of the Newtonsoft.Json file.
  3.  The subsequent failures are due to failure number 2. Since the VMDK is not returned properly the resulting operations do not have the information they need to run.

So I am going to do two things:

  1.  Suppress the warning and ask VMware to fix it
  2.  Add error handling so that the script ends on the first failure and does not create compounding failures

The customer needs to look into fixing the JSON library. There are some good references hereL
https://www.reddit.com/r/vmware/comments/8ifztv/issue_with_powercli_1010/<https://eu-west-1.protection.sophos.com?d=reddit.com&u=aHR0cHM6Ly93d3cucmVkZGl0LmNvbS9yL3Ztd2FyZS9jb21tZW50cy84aWZ6dHYvaXNzdWVfd2l0aF9wb3dlcmNsaV8xMDEwLw==&i=NWYwODY3M2VlYjE4NjQwZTI5NzJiN2Zk&t=ZSs5Um5oNlh3U2llUzhSQWxUdU5XL2p4cWwzUjJoVVU2QnZIWUtjUFdNQT0=&h=6f0bfd2f351e4e86b9d8bd94ead5432f>
https://stackoverflow.com/questions/32794225/could-not-load-file-or-assembly-newtonsoft-json-version-7-0-0-0<https://eu-west-1.protection.sophos.com?d=stackoverflow.com&u=aHR0cHM6Ly9zdGFja292ZXJmbG93LmNvbS9xdWVzdGlvbnMvMzI3OTQyMjUvY291bGQtbm90LWxvYWQtZmlsZS1vci1hc3NlbWJseS1uZXd0b25zb2Z0LWpzb24tdmVyc2lvbi03LTAtMC0w&i=NWYwODY3M2VlYjE4NjQwZTI5NzJiN2Zk&t=U2s5M0VyclBCeWUzbG41bThta25rTkNGL3YzWG5JK0hWNWo2Zjl3TzBVdz0=&h=6f0bfd2f351e4e86b9d8bd94ead5432f>

There are many more. They can either do that, or use a newer version of Windows altogether (2016+)

**Comment by PascalStordata** [comment]
Hello,

Did you manage to fix the following points please?
1.	Suppress the warning and ask VMware to fix it
2.	Add error handling so that the script ends on the first failure and does not create compounding failures

Please find below some news from the end customer:

I also did the test on a Windows 2016 server and I find myself with the same concern regarding the following errors:
Could not load file or assembly 'Newtonsoft.Json, Version = 10.0.0.0, Culture = neutral, PublicKeyToken = 30ad4fe6b2a6aeed' or one of
its dependencies. The system cannot find the file specified

Actually this is a problem with vmware.powercli 12.1.0 ***, with powercli 12.0.0. ***** I don't have these messages.

Thank you

Best regards
Pascal LE FLOCH 
Stordata

**Comment by codyhosterman** [comment]
The error suppression is added in 2.2.0.2.

As for the JSON error, this could be using standard PowerShell, not PowerShell core. I would recommend using PowerShell 7. Though I cannot replicate that error so far with these cmdlets.
