### ISSUE TITLE
New vmfs volume from replicated protection group snapshot fails on invalid volume name

### ISSUE THREAD

**Issue by will-lamm** [PureStorage-OpenConnect/PureStorage.FlashArray.VMware#8]
Protection group replicated snapshot from arrayA to arrayB is named arraya:protectiongroup.snapshotsuffix.volumegroup/volumename which fails on new-pfavolume with invalid name.  Tried without volumegroup with the same result.  Seems like colon in the snapshot name is being passed to new-pfavolume and returning the following error:

`New-PfaVolVmfsFromSnapshot -cluster $arraybcluster -flasharray $arrayb -snapName arraya:protectiongroup.snapshotsuffix.volumegroup/volumename`

`New-PfaVolume : [{"msg": "Volume name must be between 1 and 63 characters (alphanumeric, '_' and '-') in length and begin and end with a letter or number. The name must include at least one letter.", "code": 19, "ctx": 
"ArrayA:ProtectionGroup-snap-5862"}]
At C:\Program Files\WindowsPowerShell\Modules\PureStorage.FlashArray.VMware.VMFS\1.1.0.2\PureStorage.FlashArray.VMware.VMFS.psm1:717 char:12`
`+   $newVol =New-PfaVolume -Array $flasharray -Source $snapName -Volume ...`
`+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PfaVolume], PureRestException
    + FullyQualifiedErrorId : PurePowerShell.NewVolumeCmdlet`

Need a parameter to rename the newly copied volume on arrayb.

**Comment by codyhosterman** [comment]
I auto-generate the name when creating from a snapshot and when the snapshot is a pgroup snapshot and/or is in a volume group it wasnt parsing properly. I fixed this in the 1.4.1.2 release of the module. Test it and let me know.

**Comment by codyhosterman** [comment]
Fix confirmed by reporter.
