### ISSUE TITLE
Issue with Uninstall-PfavSpherePlugin

### ISSUE THREAD

**Issue by codyhosterman** [PureStorage-OpenConnect/PureStorage.FlashArray.VMware#9]
There has been a reported issue around the uninstaller not uninstalling the plugin. No details yet, but opening this issue to track the issue.

**Comment by dstamen** [comment]
Any details if this is a particular VC version? Flash or H5?

**Comment by codyhosterman** [comment]
Dunno. It was reported awhile back but couldnt be reproduced, I am going to keep this open until I get a chance to vet it. Or if no one hits in a few months and I dont get to testing it I will just close it. Whichever comes first

**Comment by codyhosterman** [comment]
Could not reproduce.
